#define MOBILE_START_TRANSMIT '{'
#define MOBILE_END_TRANSMIT '}'
#define ROBOT_START_TRANSMIT '['
#define ROBOT_END_TRANSMIT ']'

#define ROBOT_JOYSTICK_CONTROL '&'


#define MODULE_DATA_TYPE_REQUEST '!'

#define MODULE_DATA_MODULE_INFO '#'

#define MODULE_DATA_MODULE_NAME '%'
#define MODULE_DATA_MODULE_CREATOR '^'


#define MODULE_DATA_MODULE_STATUS '$'

#define MODULE_ATTACK_CD 'y'
#define MODULE_ATTACK_READY 'u'


#define MODULE_DATA_TYPE_CONTROL '@'

#define MODULE_ACTION_ATTACK 'q'
#define MODULE_ACTION_LEFT 'w'
#define MODULE_ACTION_RIGHT 'e'
#define MODULE_ACTION_UP 'r'
#define MODULE_ACTION_DOWN 't'


//Wire I2C Communication
#define MASTER_ADDRESS 25
#define SLAVE_ADDRESS 42
#define WIRE_DATA_SIZE 2

